Repository BitcreditProtocol/E-Bill-frontend, pull requests merged in 2024-11, with the labels that each got.

#23 Identity creation flow
  src/assets/encrypted-data-illustration.svg
  src/assets/success-illustration.svg
  src/components/DocumentUpload.tsx
  src/components/ui/input.tsx
  src/components/ui/select.tsx
  src/constants/routes.ts
  src/main.tsx
  src/pages/onboarding/ConfirmIdentity.tsx
  src/pages/onboarding/CreateIdentity.tsx
  src/pages/onboarding/CreateNewIdentity.tsx
  src/pages/onboarding/EmailVerification.tsx
  src/pages/onboarding/OptionalInformation.tsx
  src/pages/onboarding/RequiredInformation.tsx
  src/pages/onboarding/Success.tsx
  src/utils/index.ts
Labels: enhancement

#62 fix(font): add GeistMono webfonts
  index.html
  src/assets/fonts/GeistMono-Medium.woff2
  src/assets/fonts/GeistMono-Regular.woff2
  tailwind.config.js
Labels: enhancement

#63 chore(ui): bigger check icon on medium size checkbox
  src/components/ui/checkbox.tsx
Labels: enhancement

#68 chore(lint): upgrade es-lint and fix some warnings
  package-lock.json
  package.json
  src/components/ui/button.tsx
  src/hooks/useEnvironmentAwareAction.ts
  src/pages/RecoverWithPrivateKey.tsx
Labels: dependencies

#79 Update README.md
  README.md
Labels: documentation

#71 ui(i18n): format numbers on Bills page
  src/components/FormattedCurrency.test.tsx
  src/components/FormattedCurrency.tsx
  src/pages/Bills.tsx
  vite.config.ts
Labels: i18n, enhancement

#95 ui(storybook): basic stories for button component
  .storybook/preview.ts
  src/components/ui/button.stories.tsx
Labels: enhancement

#100 chore(lint): apply storybook eslint rules
  eslint.config.js
  package.json
Labels: i18n

#106 feat(i18n): setup Crowdin
  .github/workflows/crowdin.yml
  .lintstagedrc.json
  crowdin.yml
  package.json
  src/context/language/LanguageContext.ts
  src/context/language/LanguageProvider.test.tsx
  src/context/language/LanguageProvider.tsx
  src/i18n/en.json
  src/i18n/source.json
  src/pages/signup/OptionalInformation.tsx
  src/utils/index.ts
Labels: i18n, enhancement
