Repository BitcreditProtocol/E-Bill-frontend, pull requests merged in 2025-02, with the labels that each got.

#239 New Crowdin Translations
  src/i18n/ach-UG/translation.json
  src/i18n/de-AT/translation.json
  src/i18n/en-US/translation.json
  src/i18n/es-AR/translation.json
  src/i18n/it-IT/translation.json
  src/i18n/tr-TR/translation.json
Labels: i18n, automated

#275 docs: add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#283 Copy to clipboard button component
  src/components/CopyToClipboardButton.tsx
  src/components/Summary.tsx
  src/i18n/source.json
  src/pages/bills/Offer.tsx
  src/pages/bills/Pay.tsx
  src/pages/bills/Payment.tsx
  src/pages/bills/mint/components/EcashToken.tsx
  src/pages/company/Edit.tsx
  src/pages/contacts/Create.tsx
  src/pages/contacts/View.tsx
  src/pages/identity/Edit.tsx
Labels: new feature, enhancement
